apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-inventory-config
  namespace: retail-inventory
data:
  # Database Configuration
  DB_NAME: "retail_inventory"
  DB_USERNAME: "retail_user"
  DB_PORT: "5432"

  # Redis Configuration
  REDIS_PORT: "6379"

  # API Configuration
  SPRING_API_PORT: "8080"
  ML_API_PORT: "8000"
  FRONTEND_PORT: "3000"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "https://yourdomain.com,https://www.yourdomain.com"

  # Monitoring
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3001"
  GRAFANA_ADMIN_USER: "admin"

  # Application Configuration
  SPRING_PROFILES_ACTIVE: "prod"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
