apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
  namespace: retail-inventory
  labels:
    app: spring-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
        - name: spring-api
          image: your-registry/retail-inventory-spring-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: retail-inventory-config
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: retail-inventory-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: retail-inventory-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: retail-inventory-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-inventory-secrets
                  key: DB_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: retail-inventory-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-inventory-secrets
                  key: REDIS_PASSWORD
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: retail-inventory-config
                  key: CORS_ALLOWED_ORIGINS
            - name: ML_API_BASEURL
              value: "http://ml-api:8000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: retail-inventory-secrets
                  key: JWT_SECRET
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: spring-api
  namespace: retail-inventory
spec:
  selector:
    app: spring-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-api-hpa
  namespace: retail-inventory
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
